name: example
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+100

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  halo_state:
    path: ../

  flutter_riverpod:
  package_info_plus:
  halo:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
