name: example
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+100

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  halo_state:
    path: ../

  flutter_riverpod:
  package_info_plus:
  halo:
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  adaptive_dialog: ^2.4.1
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
