include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    no_leading_underscores_for_local_identifiers: false
    prefer_function_declarations_over_variables: false
    prefer_interpolation_to_compose_strings: false
    library_private_types_in_public_api: false

    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
