name: halo_state
description: Personal flutter state management package
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  collection: # https://pub.dev/packages/collection
  flutter_riverpod: # https://pub.dev/packages/flutter_riverpod
  halo: # https://pub.dev/packages/halo
  package_info_plus: # https://pub.dev/packages/package_info
  path_provider: # https://pub.dev/packages/path_provider
  riverpod: # https://pub.dev/packages/riverpod

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
